# Generated by Django 5.1.6 on 2025-03-20 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thrift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Online', 'Khalti'), ('Esewa', 'Esewa')], default='Cash On Delivery', max_length=20),
        ),
    ]
